// Auto-generated by ml/policy_mlp.py::export_c_header -- do not edit by hand.
// Regenerate after retraining. See ml/README.md for the training pipeline.
#pragma once

static const float POLICY_X_MEAN[1] = {786.1f};
static const float POLICY_X_SCALE[1] = {154.26142f};
static const float POLICY_Y_MEAN[3] = {0.6f, 8.4313725f, 796.99098f};
static const float POLICY_Y_SCALE[3] = {1.0f, 85.080643f, 162.62994f};
static const float POLICY_W0[8] = {0.33998125f, -0.079291043f, -1.163185f, 1.8188691f, 0.65377651f, 0.24713059f, -0.10026559f, 3.1925297f};
static const float POLICY_B0[8] = {1.6556579f, -0.53041439f, -0.90176463f, -0.12915805f, -0.026517473f, 0.68445827f, -0.70049518f, -0.010498129f};
static const float POLICY_W1[64] = {-1.8144188f, -0.45992905f, -0.052833076f, 0.97194658f, 0.22552748f, -0.80907703f, -0.3655783f, 0.72827558f, 0.18208733f, 0.27565451f, 0.1478903f, -0.080008376f, -0.41359167f, -0.22253469f, -0.15816888f, 0.077673773f, 0.8784452f, -0.42679809f, -0.67866888f, 0.70302657f, -0.14482822f, 0.43447519f, 0.38675458f, -0.15379952f, 0.15063701f, 0.35638547f, -0.26293973f, -0.29226357f, 0.20966672f, -0.62012643f, -0.48543991f, -2.5702148f, 0.81154524f, 0.12083758f, -0.46490563f, 0.20141168f, 0.42313314f, -0.07521505f, 0.40717911f, -0.34375291f, 0.84711788f, -0.10282113f, 0.21808991f, -0.35371313f, -0.62086926f, -0.37859097f, -0.48664823f, -1.2597946f, 0.20931556f, -0.36819692f, 0.87136203f, -0.41235319f, -0.31690264f, 0.38317672f, 0.57407092f, -1.1063644f, 0.25797069f, 0.33041549f, 0.1169691f, -0.44709495f, -0.40807743f, -0.46813443f, -0.037771174f, -0.45938289f};
static const float POLICY_B1[8] = {-1.5498791f, -0.5485458f, 0.051671178f, 0.70932403f, 0.040306181f, 0.10363139f, 0.76121766f, -0.5665646f};
static const float POLICY_W2[24] = {0.0037157366f, 0.18506506f, -0.0017975901f, -0.0096988699f, -0.011601596f, 0.020671224f, -0.015509172f, 0.65787158f, 1.9279133f, -0.51683699f, 0.16387954f, 2.9130827f, 0.95562061f, -1.7394075f, 1.9540647f, -0.07707435f, -0.66039765f, 0.3638803f, 1.0749307f, -0.66885347f, 0.1177179f, -0.16888651f, 0.22798442f, 0.50234371f};
static const float POLICY_B2[3] = {0.018099436f, -2.6744076f, -2.1104438f};

// layer shapes (in, out): [(1, 8), (8, 8), (8, 3)]
static inline void policy_forward(float rpm_upper, float out[3]) {
    float x0 = (rpm_upper - POLICY_X_MEAN[0]) / POLICY_X_SCALE[0];
    float h0[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B0[o];
        acc += POLICY_W0[o] * x0;
        h0[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h1[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B1[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W1[o * 8 + j] * h0[j];
        h1[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h2[3];
    for (int o = 0; o < 3; o++) {
        float acc = POLICY_B2[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W2[o * 8 + j] * h1[j];
        out[o] = acc * POLICY_Y_SCALE[o] + POLICY_Y_MEAN[o];
    }
}
