// Auto-generated by ml/policy_mlp.py::export_c_header -- do not edit by hand.
// Regenerate after retraining. See ml/README.md for the training pipeline.
#pragma once

static const float POLICY_X_MEAN[1] = {900.0f};
static const float POLICY_X_SCALE[1] = {176.63522f};
static const float POLICY_Y_MEAN[3] = {0.6f, -23.921569f, 905.05882f};
static const float POLICY_Y_SCALE[3] = {1.0f, 9.0917828f, 176.65269f};
static const float POLICY_W0[8] = {-3.2508607f, 0.14701478f, -2.3591086f, 1.3543308f, 0.29735142f, 1.2661651f, -0.10177261f, 2.0397156f};
static const float POLICY_B0[8] = {0.31986937f, -0.34960822f, 0.58067548f, -0.31756157f, -0.51013658f, 1.8292632f, -0.70049518f, 0.31585437f};
static const float POLICY_W1[64] = {-0.87611409f, -0.46684193f, -1.8308255f, -0.61220348f, 0.014065603f, 0.73140572f, -0.37107306f, 1.8980007f, 0.084158578f, 0.17216286f, -0.1141056f, -0.082228459f, -0.21297993f, -0.47424912f, -0.16054621f, 0.1310451f, 0.33796984f, -0.43617104f, -1.7461003f, 0.49674643f, 0.00038508591f, 0.17266165f, 0.39256762f, 0.61234469f, 2.8160144f, 0.43434923f, -0.2317833f, -0.3943499f, 0.27528655f, 0.61962876f, -0.49273623f, -0.48569533f, 0.2119502f, 0.047074189f, 0.16235553f, 0.11321529f, 0.54058535f, -2.1739271f, 0.41329915f, -0.2505877f, 1.9385911f, -0.10436656f, 2.140584f, 0.19223603f, -0.4866904f, -1.2237095f, -0.49396271f, -0.52659906f, -0.87989488f, -0.3688342f, 0.72983581f, 0.39491006f, -0.2859052f, 1.0693857f, 0.58269939f, 0.38231485f, 0.052099341f, 0.33538174f, 0.15454244f, -0.45381493f, -0.41421097f, -1.0232292f, -0.038338887f, -0.46628757f};
static const float POLICY_B1[8] = {-1.5264161f, -0.42716391f, -0.63824222f, 0.16905019f, -0.72790247f, 0.54649512f, 1.288341f, -0.51760013f};
static const float POLICY_W2[24] = {0.065032629f, 0.24140261f, -0.030537002f, 0.15739461f, -0.15718559f, -0.096985439f, -0.012253131f, 0.19749492f, 2.7678791f, -0.53151281f, -1.9994158f, 3.8474158f, -1.9576211f, -2.6277521f, -1.4466333f, -1.2044588f, -0.10506136f, 0.33031022f, 0.45212137f, -0.32113477f, 0.24044808f, 0.11645992f, 0.067406403f, 0.7845143f};
static const float POLICY_B2[3] = {-0.24916442f, -2.0279604f, 0.41921569f};

// layer shapes (in, out): [(1, 8), (8, 8), (8, 3)]
static inline void policy_forward(float rpm_upper, float out[3]) {
    float x0 = (rpm_upper - POLICY_X_MEAN[0]) / POLICY_X_SCALE[0];
    float h0[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B0[o];
        acc += POLICY_W0[o] * x0;
        h0[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h1[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B1[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W1[o * 8 + j] * h0[j];
        h1[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h2[3];
    for (int o = 0; o < 3; o++) {
        float acc = POLICY_B2[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W2[o * 8 + j] * h1[j];
        out[o] = acc * POLICY_Y_SCALE[o] + POLICY_Y_MEAN[o];
    }
}
