"""
ml_scripts/rule_policy.py -- a deterministic, hand-coded placeholder controller with the
*exact same call interface* as the trained PolicyMLP (ml_scripts/policy_mlp.py). It exists so
the embedded/control-loop code can be written, wired up, and visually verified end to
end right now, before any real CFD data or trained model exists -- then swapped for
the real PolicyMLP later with zero changes to whatever calls it.

Rule (as specified, not derived from any data -- this is a stand-in, not a model):

    rpm_lower  = rpm_upper                          (lower rotor mirrors upper RPM 1:1)
    azimuth_deg =  45   if rpm_upper <  500
                =  90   if 500 <= rpm_upper <= 900
                = 135   if rpm_upper >  900
    spacing_m  = DEFAULT_SPACING                     (held fixed -- see note below)

spacing_m note: the interface match with PolicyMLP requires all three outputs
(spacing_m, azimuth_deg, rpm_lower), but the rule you specified only defines RPM and
azimuth. DEFAULT_SPACING below is an arbitrary placeholder (0.40 m -- not derived
from the design space's actual spacing grid, run_sweep.py's DESIGN_SPACE_DUAL
spacing_m = [0.05, 0.10, 0.20, 0.35, 0.60]) -- it carries no engineering meaning yet
and should be replaced once there's an actual reason to vary it.
"""
from __future__ import annotations

from dataclasses import dataclass
import numpy as np

DEFAULT_SPACING = 0.40  # m -- arbitrary placeholder, see module docstring


def rule_forward(rpm_upper: float, spacing_m: float = DEFAULT_SPACING) -> tuple[float, float, float]:
    """Single-value version of the rule. Returns (spacing_m, azimuth_deg, rpm_lower)
    to match PolicyMLP output column order (ml_scripts.policy_mlp.POLICY_OUTPUT_COLS)."""
    if rpm_upper < 500:
        azimuth_deg = 45.0
    elif rpm_upper <= 900:
        azimuth_deg = 90.0
    else:
        azimuth_deg = 135.0
    rpm_lower = rpm_upper
    return (spacing_m, azimuth_deg, rpm_lower)


@dataclass
class RulePolicy:
    """Drop-in replacement for ml_scripts.policy_mlp.PolicyMLP -- same .predict() shape
    (N, 3) -> [spacing_m, azimuth_deg, rpm_lower], no training, no scalers."""
    spacing_m: float = DEFAULT_SPACING

    def predict(self, rpm_upper) -> np.ndarray:
        rpm_arr = np.atleast_1d(np.asarray(rpm_upper, dtype=float))
        rows = [rule_forward(u, self.spacing_m) for u in rpm_arr]
        return np.array(rows, dtype=float)


def export_c_header(path: str, fn_name: str = "policy_forward",
                     spacing_m: float = DEFAULT_SPACING):
    """
    Emits the same `void policy_forward(float rpm_upper, float out[3])` signature as
    ml_scripts.policy_mlp.export_c_header, implemented as plain if/else instead of matrix
    multiplies. Embedded code can #include either header interchangeably -- swap
    rule_policy.h for policy_mlp.h once a real model exists, no call-site changes.
    """
    lines = [
        "// Auto-generated by ml_scripts/rule_policy.py::export_c_header -- do not edit by hand.",
        "// Deterministic placeholder controller -- NOT a trained model. See",
        "// ml_scripts/rule_policy.py module docstring. Same signature as policy_mlp.h's",
        "// policy_forward() so this can be swapped for the trained MLP with no",
        "// call-site changes once real CFD data exists.",
        "#pragma once",
        "",
        f"#define POLICY_DEFAULT_SPACING_M {spacing_m:.6f}f",
        "",
        f"static inline void {fn_name}(float rpm_upper, float out[3]) {{",
        f"    out[0] = POLICY_DEFAULT_SPACING_M;  // spacing_m (placeholder, not rule-derived)",
        f"    if (rpm_upper < 500.0f) {{",
        f"        out[1] = 45.0f;",
        f"    }} else if (rpm_upper <= 900.0f) {{",
        f"        out[1] = 90.0f;",
        f"    }} else {{",
        f"        out[1] = 135.0f;",
        f"    }}",
        f"    out[2] = rpm_upper;  // rpm_lower mirrors rpm_upper 1:1",
        f"}}",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
