// Auto-generated by ml/policy_mlp.py::export_c_header -- do not edit by hand.
// Regenerate after retraining. See ml/README.md for the training pipeline.
#pragma once

static const float POLICY_X_MEAN[1] = {786.1f};
static const float POLICY_X_SCALE[1] = {154.26142f};
static const float POLICY_Y_MEAN[3] = {0.33333333f, -75.0f, 773.35961f};
static const float POLICY_Y_SCALE[3] = {0.18856181f, 21.213203f, 105.64555f};
static const float POLICY_W0[8] = {-0.15881446f, -0.22295293f, -0.60915723f, 4.5184198f, 2.4294186f, 5.2220114f, -0.10169305f, 2.7119963f};
static const float POLICY_B0[8] = {1.0296378f, -0.59018759f, 1.7528961f, -2.3623852f, -3.3012413f, 1.4198587f, -0.70049518f, -2.4326224f};
static const float POLICY_W1[64] = {-0.93627813f, -0.46647695f, -1.7428264f, 0.96986048f, -4.4520378f, -0.19514217f, -0.37078295f, 2.2555169f, -0.10351709f, 0.17310201f, -0.19007328f, -0.094415276f, -0.30237092f, -0.70342088f, -0.1604207f, 0.091588909f, 0.3399136f, -0.43583004f, -0.59873294f, -0.15878528f, 0.08578198f, -0.51385061f, 0.39226071f, -0.11857902f, 0.021623468f, 0.29550165f, 0.19345739f, -0.66185896f, 0.30686546f, -1.715529f, -0.492351f, -0.79585528f, 0.91565096f, 0.083916278f, 0.21075225f, -0.043287698f, 0.44240218f, -5.9302462f, 0.41297602f, -0.20619461f, -0.58634032f, -0.10428496f, -0.41434006f, 0.20852319f, -0.48630989f, -0.44512353f, -0.49357653f, -0.46412806f, -0.34727423f, -0.35576502f, 0.78851754f, -5.4280245f, -0.24962487f, 0.06593505f, 0.58224382f, -3.7690666f, -0.29898632f, 0.33511953f, -0.16086023f, -0.45346013f, -0.41388713f, -0.4370447f, -0.038308913f, -0.46592302f};
static const float POLICY_B1[8] = {-1.7469472f, -0.82212262f, -0.83337601f, -0.12060573f, -1.0250912f, -0.83873571f, -0.51026946f, -0.89111966f};
static const float POLICY_W2[24] = {3.1211844f, 0.25405337f, -0.26700398f, -2.2112851f, -4.5437444f, 0.061253188f, 3.5790158f, 0.50982204f, 3.1179205f, -0.50325977f, -0.42299027f, -1.9740647f, -4.6771371f, -0.27285213f, 3.5666891f, -0.0032623454f, -1.384828f, 0.33516103f, 0.14494665f, 0.31731154f, 3.493932f, 0.68620759f, -4.3317062f, 0.55230851f};
static const float POLICY_B2[3] = {-0.72202174f, -0.72001298f, 1.5298397f};

// layer shapes (in, out): [(1, 8), (8, 8), (8, 3)]
static inline void policy_forward(float rpm_upper, float out[3]) {
    float x0 = (rpm_upper - POLICY_X_MEAN[0]) / POLICY_X_SCALE[0];
    float h0[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B0[o];
        acc += POLICY_W0[o] * x0;
        h0[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h1[8];
    for (int o = 0; o < 8; o++) {
        float acc = POLICY_B1[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W1[o * 8 + j] * h0[j];
        h1[o] = acc > 0.0f ? acc : 0.0f;  // ReLU
    }
    float h2[3];
    for (int o = 0; o < 3; o++) {
        float acc = POLICY_B2[o];
        for (int j = 0; j < 8; j++) acc += POLICY_W2[o * 8 + j] * h1[j];
        out[o] = acc * POLICY_Y_SCALE[o] + POLICY_Y_MEAN[o];
    }
}
